force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Used to evaluate BBQ budgets, including scores and organizer observations.</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>Assessment-{000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/BBQ_Budget__c.field-meta.xml
<CustomField>
    <fullName>BBQ_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field of relationship with the object Roasted Budget</description>
    <label>BBQ Budget</label>
    <referenceTo>BBQ_Budget__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <description>Text area field representing comments on the grade given.</description>
    <label>Observations</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score assigned by the organizers, with a range from 0 to 10.</description>
    <label>Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BBQ_Budget__c/BBQ_Budget__c.object-meta.xml
<CustomObject>
    <description>Used to manage BBQ event budgets, including related items, contacts, and evaluations</description>
    <label>BBQ Budget</label>
    <nameField>
        <label>Roasted budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBQ Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BBQ_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In process of approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EvaluationController.cls
public with sharing class EvaluationController {
    //Ver cual es el status del presupuesto
    @AuraEnabled
    public static String getBBQStatus(Id recordId){
        BBQ_Budget__c budget = [SELECT Status__c FROM BBQ_Budget__c WHERE Id = :recordId LIMIT 1];
        return budget.Status__c;
    }

    //conecta los componentes con la lógica de Apex
    @AuraEnabled
    public static void saveEvaluation(Id recordId, Integer score, String observations){
        Assessment__c evaluation = new Assessment__c();
        evaluation.BBQ_Budget__c = recordId;
        evaluation.Score__c = score;
        evaluation.Observations__c = observations;
        insert evaluation;
    }
    
}