force-app/main/default/objects/BBQ_Budget__c/BBQ_Budget__c.object-meta.xml
<CustomObject>
    <description>Used to manage BBQ event budgets, including related items, contacts, and evaluations</description>
    <label>BBQ Budget</label>
    <nameField>
        <label>Roasted budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBQ Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BBQ_Budget__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Time field representing the date of the roast budget</description>
    <label>End</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BBQ_Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In process of approval</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelBudgetBatch.cls
public with sharing class CancelBudgetBatch implements Database.Batchable<SObject>{
    // Query inicial para obtener presupuestos no realizados y vencidos
    public Database.QueryLocator start (Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Status__c, End__c
            FROM BBQ_Budget__c
            //WHERE Status__c = 'Cancelled' AND End__c < TODAY 
            WHERE End__c < TODAY 

        ]);
    }

    //Procesar los registros por lotes y cambiar estado a Cancelled
    public void execute(Database.BatchableContext bc, List<BBQ_Budget__c> scope){
        for (BBQ_Budget__c presupuesto : scope){
            presupuesto.Status__c = 'Cancelled';
        }
        update scope;
    }

    // Finalizar el batch
    public void finish(Database.BatchableContext bc){
        System.debug('End Batch. cancelled Budget');
    }
}